name: dart_package_1
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  mysql1: ^0.19.1  # The package for MySQL connection
  crypto: ^3.0.0   # The package for hashing and cryptographic operations
 

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
